### ISSUE TITLE
Cringo! fails in DMs due to not being in a guild

### ISSUE THREAD

**Issue by williammck** [crimsobot/crimsoBOT#46]
Since some of the logic in Cringo! expects the discord.py Context to have a Guild present, when playing in DMs, Cringo! throws an exception at the end when it's trying to add the server bonus.

![image](https://user-images.githubusercontent.com/1619328/77384661-ee8aac00-6d53-11ea-857a-270c108845b9.png)

Applicable logs:
```
Mar 24 02:37:19 crimsobot pipenv[25199]: [2020-03-24 02:37:19]    ERROR: Invoke: husking#1343 // >cringo: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'        (crimsobot.bot)
Mar 24 02:37:19 crimsobot pipenv[25199]: Traceback (most recent call last):
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/home/crimsobot/.local/share/virtualenvs/crimsobot-QqJWrQb0/lib/python3.6/site-packages/discord/ext/commands/core.py", line 83, in wrapped
Mar 24 02:37:19 crimsobot pipenv[25199]:     ret = await coro(*args, **kwargs)
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/opt/crimsobot/crimsobot/cogs/cringo.py", line 51, in cringo
Mar 24 02:37:19 crimsobot pipenv[25199]:     await self.cringo_main(ctx, 4)
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/opt/crimsobot/crimsobot/cogs/cringo.py", line 253, in cringo_main
Mar 24 02:37:19 crimsobot pipenv[25199]:     if ctx.guild.id == 552650672965943296:
Mar 24 02:37:19 crimsobot pipenv[25199]: AttributeError: 'NoneType' object has no attribute 'id'
Mar 24 02:37:19 crimsobot pipenv[25199]: The above exception was the direct cause of the following exception:
Mar 24 02:37:19 crimsobot pipenv[25199]: Traceback (most recent call last):
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/home/crimsobot/.local/share/virtualenvs/crimsobot-QqJWrQb0/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 892, in invoke
Mar 24 02:37:19 crimsobot pipenv[25199]:     await ctx.command.invoke(ctx)
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/home/crimsobot/.local/share/virtualenvs/crimsobot-QqJWrQb0/lib/python3.6/site-packages/discord/ext/commands/core.py", line 1239, in invoke
Mar 24 02:37:19 crimsobot pipenv[25199]:     await super().invoke(ctx)
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/home/crimsobot/.local/share/virtualenvs/crimsobot-QqJWrQb0/lib/python3.6/site-packages/discord/ext/commands/core.py", line 797, in invoke
Mar 24 02:37:19 crimsobot pipenv[25199]:     await injected(*ctx.args, **ctx.kwargs)
Mar 24 02:37:19 crimsobot pipenv[25199]:   File "/home/crimsobot/.local/share/virtualenvs/crimsobot-QqJWrQb0/lib/python3.6/site-packages/discord/ext/commands/core.py", line 92, in wrapped
Mar 24 02:37:19 crimsobot pipenv[25199]:     raise CommandInvokeError(exc) from exc
Mar 24 02:37:19 crimsobot pipenv[25199]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by h-anjru** [comment]
Issue resolved: https://github.com/crimsobot/crimsoBOT/pull/48
